# Generated by Django 6.0.3 on 2026-04-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("awaiting_ocr", "Awaiting OCR"),
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("discarded", "Discarded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
