# Generated by Django 6.0.3 on 2026-08-21 23:02

from django.db import migrations, models

import ingest.models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0002_alter_scanresult_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanresult",
            name="image",
            field=models.ImageField(
                blank=True, upload_to=ingest.models.staging_image_path
            ),
        ),
    ]
