# Generated by Django 6.0.3 on 2026-09-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0003_alter_scanresult_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanresult",
            name="ocr_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
