# Generated by Django 6.1.1 on 2026-09-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0004_scanresult_ocr_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiusagelog",
            name="produced_reading",
            field=models.BooleanField(default=False),
        ),
    ]
