# Generated by Django 6.0.3 on 2026-04-06 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("name_romanized", models.CharField(blank=True, max_length=500)),
                ("viaf_id", models.CharField(blank=True, db_index=True, max_length=50)),
                ("variant_names", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("name_romanized", models.CharField(blank=True, max_length=500)),
                ("place", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=500)),
                ("heading_romanized", models.CharField(blank=True, max_length=500)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[("LC", "LC"), ("NLI", "NLI"), ("local", "Local")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["heading"],
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, blank=True, max_length=255),
                ),
                ("title", models.CharField(max_length=500)),
                ("title_romanized", models.CharField(blank=True, max_length=500)),
                ("subtitle", models.CharField(blank=True, max_length=500)),
                (
                    "date_of_publication",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "date_of_publication_display",
                    models.CharField(blank=True, max_length=100),
                ),
                ("place_of_publication", models.CharField(blank=True, max_length=255)),
                ("language", models.CharField(blank=True, max_length=50)),
                ("source_marc", models.JSONField(blank=True, null=True)),
                (
                    "source_catalog",
                    models.CharField(
                        blank=True,
                        choices=[("NLI", "NLI"), ("LC", "LC")],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True, related_name="records", to="catalog.author"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locations",
                    models.ManyToManyField(
                        blank=True, related_name="records", to="catalog.location"
                    ),
                ),
                (
                    "publishers",
                    models.ManyToManyField(
                        blank=True, related_name="records", to="catalog.publisher"
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True, related_name="records", to="catalog.subject"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("title_romanized", models.CharField(blank=True, max_length=500)),
                ("total_volumes", models.IntegerField(blank=True, null=True)),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="series_set",
                        to="catalog.publisher",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "series",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="TitlePageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="title-pages/%Y/%m/%d/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("staged", models.BooleanField(default=True)),
                (
                    "record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="title_page_images",
                        to="catalog.record",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ExternalIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[
                            ("ISBN", "ISBN"),
                            ("LCCN", "LCCN"),
                            ("NLI", "NLI Control Number"),
                            ("VIAF", "VIAF ID"),
                            ("OCLC", "OCLC Number"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identifiers",
                        to="catalog.record",
                    ),
                ),
            ],
            options={
                "ordering": ["identifier_type", "value"],
                "unique_together": {("record", "identifier_type", "value")},
            },
        ),
        migrations.CreateModel(
            name="SeriesVolume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume_number", models.CharField(max_length=50)),
                ("held", models.BooleanField(default=True)),
                (
                    "record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series_volumes",
                        to="catalog.record",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volumes",
                        to="catalog.series",
                    ),
                ),
            ],
            options={
                "ordering": ["volume_number"],
                "unique_together": {("series", "volume_number")},
            },
        ),
    ]
