# Generated by Django 6.0.3 on 2026-04-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalidentifier",
            name="identifier_type",
            field=models.CharField(
                choices=[
                    ("ISBN", "ISBN"),
                    ("LCCN", "LCCN"),
                    ("LCC", "LC Classification"),
                    ("DDC", "Dewey Decimal"),
                    ("NLI", "NLI Control Number"),
                    ("VIAF", "VIAF ID"),
                    ("OCLC", "OCLC Number"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="source_catalog",
            field=models.CharField(
                blank=True,
                choices=[("NLI", "NLI"), ("LC", "LC"), ("DNB", "DNB")],
                max_length=10,
            ),
        ),
    ]
