# Generated by Django 6.0.3 on 2026-04-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_add_dnb_source_catalog_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="cover_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
