# Generated by Django 6.0.3 on 2026-09-04 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_add_cover_url"),
        ("ingest", "0004_scanresult_ocr_started_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SeriesClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("volume_spec", models.CharField(max_length=200)),
                (
                    "originating_volume_number",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("committed", "Committed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="series_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "originating_scan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="series_claims",
                        to="ingest.scanresult",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claims",
                        to="catalog.series",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SeriesClaimRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume_number", models.CharField(max_length=50)),
                (
                    "search_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("searching", "Searching"),
                            ("found", "Found"),
                            ("no_match", "No match"),
                            ("multiple", "Multiple matches"),
                            ("manual_skip", "Skip"),
                            ("manual_held", "Mark held"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "candidate_records",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "selected_candidate_index",
                    models.IntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="catalog.seriesclaim",
                    ),
                ),
                (
                    "created_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="series_claim_rows",
                        to="catalog.record",
                    ),
                ),
            ],
            options={
                "ordering": ["volume_number"],
                "unique_together": {("claim", "volume_number")},
            },
        ),
    ]
