# Generated by Django 6.0.3 on 2026-09-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_seriesclaim_seriesclaimrow"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="provenance",
            field=models.TextField(
                blank=True,
                help_text="Ownership history of this copy: former owners, inscriptions, bookplates, stamps, and how it was acquired.",
            ),
        ),
    ]
