# Generated by Django 6.1.1 on 2026-09-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_record_provenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="statement_of_responsibility",
            field=models.TextField(
                blank=True,
                help_text="Responsibility for the work as transcribed from the item, from MARC 245 $c. Where the added entries carry no relator term, this is the only record of which contributor did what.",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="volume_part_number",
            field=models.CharField(
                blank=True,
                help_text='Designation of the part of a multi-part title this record describes, from MARC 245 $n: "Volume 2", "Bd. 4, T. 2".',
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="volume_part_title",
            field=models.CharField(
                blank=True,
                help_text='Name of that part, from MARC 245 $p: "Sefer Mishpatim". A part title, so it is as long as any other title.',
                max_length=500,
            ),
        ),
    ]
