# Generated by Django 6.1.1 on 2026-09-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_record_title_statement_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="bookplate_text",
            field=models.TextField(
                blank=True,
                help_text="Text of any bookplate pasted into this copy, including the owner's name and any motto.",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="dedication_text",
            field=models.TextField(
                blank=True,
                help_text="Text of any handwritten dedication or presentation inscription, with who wrote it for whom, if the inscription says.",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="stamp_text",
            field=models.TextField(
                blank=True,
                help_text="Text of any stamp on this copy — a library, a bookseller, a private collection. One stamp per line.",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="provenance",
            field=models.TextField(
                blank=True,
                help_text="Ownership history of this copy in prose: former owners, how it was acquired, where it has been. Transcribe a bookplate, a dedication or a stamp in its own field instead.",
            ),
        ),
    ]
