# Generated by Django 6.1.1 on 2026-09-07 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_record_ownership_marks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="cover_url",
        ),
        migrations.CreateModel(
            name="RecordCover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="covers/%Y/%m/%d/")),
                (
                    "source_url",
                    models.URLField(
                        help_text="Where the image was fetched from, kept for attribution and for re-fetching if the stored file is lost.",
                        max_length=500,
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cover",
                        to="catalog.record",
                    ),
                ),
            ],
        ),
    ]
