# Generated by Django 6.1.1 on 2026-09-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_series_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplicationProbe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("written_at", models.DateTimeField()),
            ],
        ),
    ]
